# zabrze configuration
# https://github.com/Ryooooooga/zabrze

abbrs:
  # Git abbreviations
  g: git
  gs: git status
  ga: git add
  gc: git commit
  gco: git checkout
  gp: git push
  gl: git log --oneline
  gd: git diff
  gb: git branch
  gm: git merge
  
  # Common commands
  ll: ls -la
  la: ls -A
  l: ls -CF
  
  # Directory navigation
  ..: cd ..
  ...: cd ../..
  ....: cd ../../..
  
  # Docker abbreviations
  d: docker
  dc: docker compose
  dps: docker ps
  
  # Modern CLI tools (if using eza, bat, etc.)
  cat: bat
  ls: eza 