# zabrze configuration
# https://github.com/Ryooooooga/zabrze

abbrevs:
  - name: '>/dev/null 2>&1'
    abbr: 'null'
    snippet: '>/dev/null 2>&1'
    global: true
  - name: git commit
    abbr: c
    snippet: commit
    global: true
    context: '^git\s'
    
  - name: git commit -m
    abbr: cm
    snippet: commit -m '{}'
    cursor: "{}" # optional; defaults to "{}"
    global: true
    context: '^git\s'

  - name: branch name
    abbr: B
    snippet: $(git symbolic-ref --short HEAD)
    evaluate: true
    global: true
    context: '^git\s'    # # Git abbreviations
    # g: git
    # gs: git status
    # ga: git add
    # gc: git commit
    # gco: git checkout
    # gp: git push
    # gl: git log --oneline
    # gd: git diff
    # gb: git branch
    # gm: git merged
    
    # # Common commands
    # ll: ls -la
    # la: ls -A
    # l: ls -CF
    
    # # Directory navigation
    # ..: cd ..
    # ...: cd ../..
    # ....: cd ../../..
  
    # # Docker abbreviations
    # d: docker
    # dc: docker compose
    # dps: docker ps
    
    # # Modern CLI tools (if using eza, bat, etc.)
    # cat: bat
    # ls: eza 