# Sheldon plugin configuration

shell = "zsh"

# Global apply setting for all plugins
apply = ["source"]

[plugins]

# Powerlevel10k theme
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

# Syntax highlighting
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

# Auto suggestions
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# History substring search
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

# Fast node manager
[plugins.fnm]
github = "Schniz/fnm"
apply = ["PATH", "source"]
hooks.post = "eval \"$(fnm env --use-on-cd)\""