# Sheldon plugin configuration

shell = "zsh"

# Global apply setting for all plugins
apply = ["source"]

[plugins]

# Syntax highlighting
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

# Auto suggestions
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# History substring search
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

# Fast node manager (commented out - use mise for Node.js instead)
# [plugins.fnm]
# github = "Schniz/fnm"
# apply = ["PATH", "source"]
# hooks.post = "eval \"$(fnm env --use-on-cd)\""

[plugins.compinit]
inline = 'autoload -U compinit && compinit'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
defer = "2"  # 遅延読み込み


[plugins.z]
github = "rupa/z" 

[plugins.mise-completion]
inline = 'eval "$(mise completion zsh)"'

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"