format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$java\
$kotlin\
$lua\
$php\
$ruby\
$swift\
$terraform\
$aws\
$gcloud\
$azure\
$kubernetes\
$helm\
$docker_context\
$package\
$time\
$line_break\
$character"""

# 右側のプロンプト
right_format = """$cmd_duration$status"""

# ユーザー名を無効化
[username]
disabled = true

# ホスト名を無効化
[hostname]
disabled = true

# バッテリーを無効化
[battery]
disabled = true

# ディレクトリ表示（パス表示）
# ディレクトリ表示（パス表示）
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " "
read_only_style = "red"
truncation_length = 0
truncation_symbol = "…/"
home_symbol = "~"
fish_style_pwd_dir_length = 10

# Git ブランチ
[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"
truncation_length = 20
truncation_symbol = "…"

# Git ステータス
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
stashed = '$${count}'
untracked = "?${count}"

# Node.js
[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "
style = "bold green"

# Python
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '
symbol = " "
style = "bold yellow"

# Rust
[rust]
format = "[$symbol($version)]($style) "
symbol = " "
style = "bold red"

# Go
[golang]
format = "[$symbol($version)]($style) "
symbol = " "
style = "bold cyan"

# Java
[java]
format = "[$symbol($version)]($style) "
symbol = " "
style = "bold red"

# Docker
[docker_context]
format = "[$symbol$context]($style) "
symbol = " "
style = "bold blue"

# AWS
[aws]
format = '[$symbol($profile)(\($region\))]($style) '
symbol = " "
style = "bold orange"

# Kubernetes
[kubernetes]
format = '[$symbol$context(\($namespace\))]($style) '
symbol = "⎈ "
style = "bold blue"
disabled = false

# 時間（日付表示）
[time]
format = "[$time]($style) "
style = "bold white"
time_format = "%Y-%m-%d %H:%M:%S"
disabled = false

# コマンド実行時間
[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"
min_time = 2000
show_milliseconds = false

# ステータス
[status]
format = "[$symbol$status]($style) "
symbol = "✘"
style = "bold red"
disabled = false

# 文字
[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
# vicmd_symbol = "[❮](bold green)"

# 改行
[line_break]
disabled = false

# # メモリ使用量
# [memory]
# format = "[$symbol${ram}]($style) "
# threshold = 70
# symbol = " "
# style = "bold dimmed white"
# disabled = false